name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        # Set the date and timestamp variables
        DATE=$(date +"%Y-%m-%d")
        TIMESTAMP=$(date +"%H%M%S")
        
        # Set the Docker tag with the desired format
        DOCKER_TAG="${DATE}-${TIMESTAMP}"

        # Build and push the Docker image with the specified tag
        docker login -u habtamu -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push habtamu/myplugin:${DOCKER_TAG}
