name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: docker login
      run: |
        docker login -u habtamu -p ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Tag and Build the Docker image
      run: |
        # Set the date and timestamp variables
        DATE=$(date +"%Y-%m-%d")
        TIMESTAMP=$(date +"%H%M%S")
        
        # Set the Docker tag with the desired format
        DOCKER_TAG="${DATE}-${TIMESTAMP}"
        docker buildx build -f ../../Dockerfile --tag habtamu/myplugin:${DOCKER_TAG} .

    - name: Push the Docker image with the specified tag
      run: docker push habtamu/myplugin:${DOCKER_TAG}