name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: docker login
      run: |
        docker login -u habtamu -p ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag habtamu/myplugin:$(date +%s)
