name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: docker login
      run: |
        docker login -u habtamu -p ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Pull an image from Docker Hub
      run: |
        docker image pull habtamu/myplugin:latest

    - name: Tag and Build the Docker image
      run: |
        # Set the date and timestamp variables
        DATE=$(date +"%Y-%m-%d")
        TIMESTAMP=$(date +"%H%M%S")
        
        # Set the Docker tag with the desired format
        DOCKER_TAG="${DATE}-${TIMESTAMP}"
        
        docker image tag habtamu/myplugin habtamu/myplugin:${DOCKER_TAG}

        # Build the Docker image
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t habtamu/myplugin:${DOCKER_TAG} .

    - name: Publish the Docker image with the specified tag
      run: docker image push